<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Haggly.Modules.MarketManagement.Application/Haggly.Modules.MarketManagement.Application.csproj" />
    <ProjectReference Include="../Haggly.Modules.MarketManagement.Contracts/Haggly.Modules.MarketManagement.Contracts.csproj" />
  </ItemGroup>
</Project>
