// <auto-generated />
using Haggly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haggly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HagglyDbContext))]
    [Migration("20260817160000_CreateSalesOrders")]
    partial class CreateSalesOrders
    {
    }
}
